name: 'parquet_benchmark'
version: '1.0.0'
config-version: 2

profile: 'parquet_benchmark'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  parquet_benchmark:
    parquet_reconcile:
      +materialized: incremental
    benchmark:
      +materialized: table
